import * as mapModule from "./map.js";
import {
    addOperator,
    deleteOperator,
    editLoginPassword,
    editOperatorName,
    editOperatorWindow,
    loadOperators,
    loadTickets,
    saveLoginPassword,
    saveOperatorName,
    saveOperatorWindow,
} from "./operators.js";
import {
    addWindow,
    deleteWindow,
    editServices,
    editWindow,
    editWindowStatus,
    loadWindows,
    saveServices,
    saveServicesWithPriority,
    saveWindow,
    saveWindowStatus,
} from "./windows.js";
import {
    addService,
    addServiceGroup,
    deleteService,
    deleteServiceGroup,
    editServiceGroup,
    editService,
    editServiceStatus,
    loadServices,
    moveServiceGroup,
    moveService,
    saveServiceGroupAssignment,
    saveService,
    saveServiceStatus,
    toggleOperatorChoice,
	toggleTerminalVisibility,
} from "./services.js";
import { loadExtraSettings, loadStats, saveExtraSettings } from "./settings.js";
import {
    addMedia,
    deleteFromServer,
    deleteMedia,
    deletePhysicalFile,
    loadMedia,
    retryMediaJob,
    toggleInPlaylist,
    toggleMedia,
    updateProcessVideoControls,
    uploadVideoFile,
} from "./media.js";

Object.assign(window, mapModule, {
    addOperator,
    addMedia,
    addWindow,
    deleteOperator,
    deleteFromServer,
    deleteMedia,
    deletePhysicalFile,
    deleteWindow,
    editLoginPassword,
    editOperatorName,
    editOperatorWindow,
    editServices,
    editWindow,
    editWindowStatus,
    loadMedia,
    loadOperators,
    loadTickets,
    loadWindows,
    retryMediaJob,
    saveLoginPassword,
    saveOperatorName,
    saveOperatorWindow,
    saveServices,
    saveServicesWithPriority,
    saveWindow,
    saveWindowStatus,
    toggleInPlaylist,
    toggleMedia,
    updateProcessVideoControls,
    loadExtraSettings,
    loadStats,
    saveExtraSettings,
    addService,
    addServiceGroup,
    deleteService,
    deleteServiceGroup,
    editServiceGroup,
    editService,
    editServiceStatus,
    loadServices,
    moveServiceGroup,
    moveService,
    saveServiceGroupAssignment,
    saveService,
    saveServiceStatus,
    toggleOperatorChoice,
    uploadVideoFile,
	toggleTerminalVisibility,
});
